import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";

import { Header } from "@/app/components";

const urabnist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className="bg-gradient-to-tr from-slate-900 to-red-950 from-60% text-slate-100"
        >
            <body className={urabnist.className}>
                <Header />
                {children}
            </body>
        </html>
    );
}
